### PR TITLE
Adds a converter from GPS coordinates to a point located in a cartesi…

### PR DESCRIPTION
**Pull request by taylorpool**
…an system

with the unit of meter.

### CODE REVIEW

**Comment by superjax** [comment]
Hey @tpool2!

This is pretty cool!  Thanks for putting it together.  It sure can be confusing to convert from GPS to meters sometimes.

I have a couple of suggestions before merging it in to the official BYU repo.  Firstly, we should move this into the `src` folder, since it is a script, and doesn't belong in the root of the package.

Secondly, while this is a useful unit test for the explicit case you have coded, it should probably be generalized before merging in.  I would suggest either making a python library that can be imported into future scripts, or creating a proper node.  Since `fcu_common` is primarily a library repository, I think that making a library makes the most sense, especially since a full node would be a little bit trivial, and it isn't obvious how it stands alone.

I'm happy that you are interested in contributing to the main branch, What do you think about these ideas?

**Comment by taylorpool** [comment]
Hi @superjax ,

I am so sorry! This was my first time using Github, and I inadvertently sent out a request to merge my code with the master branch. I only intended to commit my files into the GPS-to-Waypoint-Conversion branch. So I apologize for bothering you all.

If you would still like me to though, I would be more than happy to complete the changes that you have suggested, and then we can see if the code can go into the master branch. It's totally up to you, and I would be completely fine either way.

I love these ideas, and I 100% support them. Thanks so much for your feedback!

**Review by superjax — APPROVED** [review]
Nice work Taylor!

I like the changes that you have made.  I'm going to pull this into the main branch!

**Comment by taylorpool** [comment]
Thank you! I'm honored!

**Pull request merged**
